output_path: '.'
output_file_name_prefix: testing

# Can be organization / folder / project w/ organization_number,
# folder_number and project number as the corresponding resource id.
root_resource_type: organization
root_resource_id: 5456546415

resource_structure:
  - resource_count: 1
    folder:
      - resource_count: 2
        folder:
          - resource_count: 10
            project:
              - resource_count: 15
                service_account: []
              - resource_count: 10
                bucket: []
              - resource_count: 5
                bigquery_dataset:
                  - resource_count: 200
                    bigquery_table: []
